import {makeModel, relation} from "./_desc";
import * as f from "./_fields";
import type {Nominal} from "./_type-helpers";
import {type UserId} from "./User";

export type AccountId = Nominal<string, "account">;
export const accountDesc = makeModel({
  name: "account",
  fields: {
    id: f.id<AccountId>(),
    subdomain: f.string({}),
    name: f.string({}),
    billingName: f.string({optional: true}),
    billingLine1: f.string({optional: true}),
    billingLine2: f.string({optional: true}),
    billingZip: f.string({optional: true}),
    billingCity: f.string({optional: true}),
    billingCountryCode: f.string({optional: true}),
    billingEmail: f.string({optional: true}),
    netGiftAmount: f.int({}),
    persona: f.string({optional: true}),
    createdAt: f.date({}),
    disabledAt: f.date({optional: true}),
    totalMediaByteUsage: f.bigint({}),
    isDisabled: f.string({}),
    milestonesEnabled: f.string({}),
    sprintsEnabled: f.string({}),
    priorityLabels: f.object({}),
    effortScale: f.object({}),
    statusChangeDurations: f.object({}),
    activeFeatureFlags: f.object({}),
    timeTrackingMode: f.string({}),
    maxTimeTrackingSegmentMsDuration: f.int({}),
    timeTrackingSwimLaneInfo: f.bool({}),
    workdays: f.string({}),
    workflowMode: f.string({}),
    isLearning: f.bool({}),
    isNonProfit: f.bool({}),
    dependenciesEnabled: f.bool({}),
    maxHandSlotCount: f.int({}),
    seats: f.int({}),
    activeProjectCount: f.int({}),
    billingType: f.string({}),
    allowInheritHeroCover: f.bool({}),
    attachmentCoverMode: f.string({}),
    staffPermission: f.string({}),
    offeringTrial: f.bool({}),
    coupon: f.object({optional: true}),
    hideCompletedCardCountForDecks: f.bool({}),
    visionBoardEnabled: f.bool({}),
    fallbackEffort: f.int({}),
    timelineScaleType: f.string({}),
    startWeekday: f.string({}),
    disabledById: f.belongsTo({optional: true}).type<UserId>(),
  },
  relations: {
    disabledBy: relation("user", {type: "belongsTo", fk: "disabledById"}),
    cards: relation("card", {type: "hasMany"}),
    invoices: relation("invoice", {type: "hasMany"}),
    cardPresets: relation("cardPreset", {type: "hasMany"}),
    attachments: relation("attachment", {type: "hasMany"}),
    discordGuilds: relation("discordGuild", {type: "hasMany"}),
    timeTrackingSegments: relation("timeTrackingSegment", {type: "hasMany"}),
    workflowItems: relation("workflowItem", {type: "hasMany"}),
    deckAssignments: relation("deckAssignment", {type: "hasMany"}),
    assigneeAssignments: relation("assigneeAssignment", {type: "hasMany"}),
    assigneeDeckAssignments: relation("assigneeDeckAssignment", {type: "hasMany"}),
    wizards: relation("wizard", {type: "hasMany"}),
    milestones: relation("milestone", {type: "hasMany"}),
    sprints: relation("sprint", {type: "hasMany"}),
    sprintConfigs: relation("sprintConfig", {type: "hasMany"}),
    handCards: relation("handCard", {type: "hasMany"}),
    resolvables: relation("resolvable", {type: "hasMany"}),
    cardUpvotes: relation("cardUpvote", {type: "hasMany"}),
    resolvableParticipants: relation("resolvableParticipant", {type: "hasMany"}),
    userReportSettings: relation("userReportSetting", {type: "hasMany"}),
    cardOrders: relation("cardOrder", {type: "hasMany"}),
    accountUserAchievements: relation("accountUserAchievement", {type: "hasMany"}),
    userInviteCodes: relation("userInviteCode", {type: "hasMany"}),
    visionBoards: relation("visionBoard", {type: "hasMany"}),
    deckSubscriptions: relation("deckSubscription", {type: "hasMany"}),
    appInstallations: relation("appInstallation", {type: "hasMany"}),
    files: relation("file", {type: "hasMany"}),
    decks: relation("deck", {type: "hasMany"}),
    queueEntries: relation("queueEntry", {type: "hasMany"}),
    visionBoardQueries: relation("visionBoardQuery", {type: "hasMany"}),
    anyDecks: relation("deck", {type: "hasMany"}),
    projects: relation("project", {type: "hasMany"}),
    archivedProjects: relation("project", {type: "hasMany"}),
    anyProjects: relation("project", {type: "hasMany"}),
    roles: relation("accountRole", {type: "hasMany"}),
    invitations: relation("userInvitation", {type: "hasMany"}),
    githubIntegration: relation("integration", {type: "hasOne"}),
    slackIntegration: relation("integration", {type: "hasOne"}),
    affiliateCodes: relation("affiliateCode", {type: "hasMany"}),
    activities: relation("activity", {type: "hasMany"}),
    stripeAccountSync: relation("stripeAccountSync", {type: "hasOne"}),
    accountOnboarding: relation("accountOnboarding", {type: "hasOne"}),
  },
  keys: ["id"],
});
